package com.mobile.bo.app.datatype;

import java.io.Serializable;
import java.util.Date;
import com.mobile.database.app.entities.CONFIGSYNCHRONIZATION;

public class Z_ConfigSyncronizationData implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 8751151483967819397L;
	private String ID;
	private Date LASTSYNCHRONIZELOV;
	private Date LASTSYNCHRONIZETABUNGAN;
	private Date LASTSYNCHRONIZETAGIHAN;
	private Date LASTSYNCHRONIZEMESSAGE;
	private Date LASTSYNCHRONIZENEWS;
	private Date LASTSYNCHRONIZESCHEDULE;
	private Date LASTSYNCHRONIZEBLACKBOX;
	
	public Z_ConfigSyncronizationData(){
		
	}
	public Z_ConfigSyncronizationData(String id,Date lov,Date tabungan,Date tagihan,Date message,Date news,Date schedule,Date blackbox){
		update(id,lov,tabungan,tagihan,message,news,schedule,blackbox);
	}
	public Z_ConfigSyncronizationData(CONFIGSYNCHRONIZATION configsynchronization) {
    	update(configsynchronization);
   	}
	public String getID() {
		return ID;
	}
	public void setID(String iD) {
		ID = iD;
	}
	public Date getLASTSYNCHRONIZELOV() {
		return LASTSYNCHRONIZELOV;
	}
	public void setLASTSYNCHRONIZELOV(Date lASTSYNCHRONIZELOV) {
		LASTSYNCHRONIZELOV = lASTSYNCHRONIZELOV;
	}
	public Date getLASTSYNCHRONIZETABUNGAN() {
		return LASTSYNCHRONIZETABUNGAN;
	}
	public void setLASTSYNCHRONIZETABUNGAN(Date lASTSYNCHRONIZETABUNGAN) {
		LASTSYNCHRONIZETABUNGAN = lASTSYNCHRONIZETABUNGAN;
	}
	public Date getLASTSYNCHRONIZETAGIHAN() {
		return LASTSYNCHRONIZETAGIHAN;
	}
	public void setLASTSYNCHRONIZETAGIHAN(Date lASTSYNCHRONIZETAGIHAN) {
		LASTSYNCHRONIZETAGIHAN = lASTSYNCHRONIZETAGIHAN;
	}
	public Date getLASTSYNCHRONIZEMESSAGE() {
		return LASTSYNCHRONIZEMESSAGE;
	}
	public void setLASTSYNCHRONIZEMESSAGE(Date lASTSYNCHRONIZEMESSAGE) {
		LASTSYNCHRONIZEMESSAGE = lASTSYNCHRONIZEMESSAGE;
	}
	public Date getLASTSYNCHRONIZENEWS() {
		return LASTSYNCHRONIZENEWS;
	}
	public void setLASTSYNCHRONIZENEWS(Date lASTSYNCHRONIZENEWS) {
		LASTSYNCHRONIZENEWS = lASTSYNCHRONIZENEWS;
	}
	public Date getLASTSYNCHRONIZESCHEDULE() {
		return LASTSYNCHRONIZESCHEDULE;
	}
	public void setLASTSYNCHRONIZESCHEDULE(Date lASTSYNCHRONIZESCHEDULE) {
		LASTSYNCHRONIZESCHEDULE = lASTSYNCHRONIZESCHEDULE;
	}
	public Date getLASTSYNCHRONIZEBLACKBOX() {
		return LASTSYNCHRONIZEBLACKBOX;
	}
	public void setLASTSYNCHRONIZEBLACKBOX(Date lASTSYNCHRONIZEBLACKBOX) {
		LASTSYNCHRONIZEBLACKBOX = lASTSYNCHRONIZEBLACKBOX;
	}
	public CONFIGSYNCHRONIZATION toRowData(){
		CONFIGSYNCHRONIZATION rowData= new CONFIGSYNCHRONIZATION();	
		rowData.setID(ID);
		rowData.setLASTSYNCHRONIZELOV(LASTSYNCHRONIZELOV);
		rowData.setLASTSYNCHRONIZETABUNGAN(LASTSYNCHRONIZETABUNGAN);
		rowData.setLASTSYNCHRONIZETAGIHAN(LASTSYNCHRONIZETAGIHAN);
		rowData.setLASTSYNCHRONIZEMESSAGE(LASTSYNCHRONIZEMESSAGE);
		rowData.setLASTSYNCHRONIZENEWS(LASTSYNCHRONIZENEWS);
		rowData.setLASTSYNCHRONIZESCHEDULE(LASTSYNCHRONIZESCHEDULE);
		rowData.setLASTSYNCHRONIZEBLACKBOX(LASTSYNCHRONIZEBLACKBOX);
		
		return rowData;
	}
	
	public void update(CONFIGSYNCHRONIZATION rowData) {
		ID = rowData.getID();
		LASTSYNCHRONIZELOV = rowData.getLASTSYNCHRONIZELOV();
		LASTSYNCHRONIZETABUNGAN = rowData.getLASTSYNCHRONIZETABUNGAN();
		LASTSYNCHRONIZETAGIHAN = rowData.getLASTSYNCHRONIZETAGIHAN();
		LASTSYNCHRONIZEMESSAGE = rowData.getLASTSYNCHRONIZEMESSAGE();
		LASTSYNCHRONIZENEWS = rowData.getLASTSYNCHRONIZENEWS();
		LASTSYNCHRONIZESCHEDULE = rowData.getLASTSYNCHRONIZESCHEDULE();
		LASTSYNCHRONIZEBLACKBOX = rowData.getLASTSYNCHRONIZEBLACKBOX();
	}
	
	public void update(String id,Date lov,Date tabungan,Date tagihan,Date message,Date news,Date schedule,Date blackbox){
		ID=id;
		LASTSYNCHRONIZELOV=lov;
		LASTSYNCHRONIZETABUNGAN=tabungan;
		LASTSYNCHRONIZETAGIHAN=tagihan;
		LASTSYNCHRONIZEMESSAGE=message;
		LASTSYNCHRONIZENEWS=news;
		LASTSYNCHRONIZESCHEDULE = schedule;
		LASTSYNCHRONIZEBLACKBOX = blackbox;
	}
}
